name: Cocogitto Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    name: release
    steps:
      - name: Semver release
        uses: cocogitto/cocogitto-action@v3
        with:
          release: true
